# 训练模型的时候要保证训练集的图片和标签的文件夹在一个目录下面，
# 并且名字为JPEGImages和JPEGImages  
#     例如：F:/Code/UnetV3/trainDataset\JPEGImages  
#           F:/Code/UnetV3/trainDataset\SegmentationClass  
# 请到src\utils.py size=(320, 240)修改模型输入输出大小即图片的H*W，后续集成到yaml文件中

data_path: 'F:/Code/UnetV3/trainDataset'
train_epch: 10                               # 训练次数
max_batch_size: 16                            # 表示每个批次的样本数量
num_classes:  5                               # 不算背景
train_lr: 0.01                               # 学习率
train_wd: 0.00                               # 正则化项的权重衰减系数，以减小模型参数的大小


model: 'UNetV3_2'
# net_list = ['UNetCB', 'UNetDC', 'VGG16UNet', 'UNetV3_2', 'UNetV3', 'UNetV4']